# Generated by Django 5.1 on 2024-09-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('location', models.TextField(max_length=300)),
                ('category', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, default='https://w7.pngwing.com/pngs/877/824/png-transparent-icon-hospital-computer-icons-medicine-others-miscellaneous-text-rectangle.png', null=True, upload_to='hospital_logo/')),
            ],
        ),
    ]
