# Generated by Django 5.1 on 2024-09-04 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('specialty', models.CharField(max_length=30)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='DD-MM-YYYY')),
                ('timeslot', models.IntegerField(choices=[(0, '08:30 - 09:00'), (1, '09:00 - 09:30'), (2, '10:00 - 10:30'), (3, '11:00 - 11:30'), (4, '12:00 - 12:30'), (5, '13:00 - 13:30'), (6, '14:00 - 14:30'), (7, '15:00 - 15:30'), (8, '16:00 - 16:30'), (9, '17:00 - 17:30'), (10, '17:30 - 18:00')])),
                ('patient_name', models.CharField(max_length=60)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('status', models.IntegerField()),
                ('booked_status', models.IntegerField(default=0))
            ],
            options={
                'unique_together': {('doctor', 'date', 'timeslot')},
            },
        ),
    ]
