# Generated by Django 5.1 on 2024-09-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_hospital_description_doctor_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='booked_status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
