# Generated by Django 5.1 on 2024-09-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_appointment_booked_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
