# Generated by Django 5.1.1 on 2024-09-04 18:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_patient_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='clinic',
            field=models.TextField(blank=True, default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='prescription',
            name='directions_for_use',
            field=models.TextField(blank=True, default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='prescription',
            name='drug_details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_weight',
            field=models.IntegerField(blank=True, default=65),
        ),
    ]
