# Generated by Django 5.1.1 on 2024-11-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_prescription_clinic_prescription_directions_for_use_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
            ],
        ),
    ]
